window.KRYPHOS_CONFIG = {
  tokenSymbol: "KRYPHOS",
  totalSupply: 1000000000,
  boostReserveTokens: 100000000,
  boostReservePercent: 10,
  nonReserveSupply: 900000000,

  // Fill these after launch. Blank values remain visibly "Not configured".
  mintAddress: "",
  boostReserveWallet: "",
  boostTreasuryWallet: "",
  creatorWallet: "",

  // Public read-only state generated by kryphos_boost/engine.mjs.
  boostStateUrl: "boost-state.json",

  // Display only. Execution always uses the live engine config/quote.
  maxPriceImpactPct: 0.5,

  rpcUrl: "https://api.mainnet-beta.solana.com",
  rpcFallbacks: ["https://solana-rpc.publicnode.com"],
  rpcTimeoutMs: 6500,
  refreshMs: 30000
};
