[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kryphos_burn = "AiAyabtePcmbsA8VSsq4JCvR2qdotL4szqbNggHYvjwS"

[programs.mainnet]
kryphos_burn = "AiAyabtePcmbsA8VSsq4JCvR2qdotL4szqbNggHYvjwS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node scripts/preflight.mjs"
